---
#              _                               _ _  ___ _ _     
#      /\      | |                             | | |/ (_) | |    
#     /  \   __| |_   ____ _ _ __   ___ ___  __| | ' / _| | |___ 
#    / /\ \ / _` \ \ / / _` | '_ \ / __/ _ \/ _` |  < | | | / __|
#   / ____ \ (_| |\ V / (_| | | | | (_|  __/ (_| | . \| | | \__ \
#  /_/    \_\__,_| \_/ \__,_|_| |_|\___\___|\__,_|_|\_\_|_|_|___/                                                           
# 
# # Configuration file for AliasBlocker by kenygamer - https://kenygamer.us.to/discord/
# In this file you can change how some things of AdvancedKills work.

# worlds: Do you want to make AdvancedKills work on specific worlds? Add comma-separated worlds, or leave blank
#  to enable all worlds.
worlds: []

# boosts: What boosts are there?  List comma-separated boosters by their multiplier. You can assign a booster to
#  groups indicidually using the permission node: advancedkills.boost.x
boosts: [2, 3, 5, 10]

# calculation:
calculation:
 # calculation.typem What is the money calculated? Please enter a number.
 #   1. = % percent of the victim's money.
 #   2. = Fixed money.
 type: 1
 
 # calculation[value]: Enter the value value. If you use a percent, you must enter a value 1-100 without the percent
 #    sign.  If you use a fixed falor, you must enter the amount of money, without the dollar sign.
 value: 10
 
# minimum-money: Enter  How much is the minimum amount of money in the victim's balance to steal money? Ideally
#  it should be to be the default EconomyAPI player money.  
minimum-money: 10

# realistic-mode: Enable realistic mode? If enabled, it will always counteract the killer earning, for exmaple if the
#  victim has 1500 $ and the money is configured to 2000 $, it will only reduce up to 1500 $.
realistic-mode: true

...